data = {'alternate_url':
    'https://hh.ru/search/vacancy?enable_snippets=true&items_on_page=10&text'
                                            '=%D1'
                                       '%81%D1%82%D0%BE%D0%BB%D1%8F%D1%80',
 'arguments': None,
 'clusters': None,
 'fixes': None,
 'found': 1065,
 'items': [{'accept_incomplete_resumes': True,
            'accept_temporary': True,
            'address': {'building': '14',
                        'city': 'Санкт-Петербург',
                        'description': None,
                        'id': '7117670',
                        'lat': 59.97269,
                        'lng': 30.352061,
                        'metro': {'lat': 59.970925,
                                  'line_id': '14',
                                  'line_name': 'Кировско-Выборгская',
                                  'lng': 30.347408,
                                  'station_id': '14.196',
                                  'station_name': 'Выборгская'},
                        'metro_stations': [{'lat': 59.970925,
                                            'line_id': '14',
                                            'line_name': 'Кировско-Выборгская',
                                            'lng': 30.347408,
                                            'station_id': '14.196',
                                            'station_name': 'Выборгская'}],
                        'raw': 'Санкт-Петербург, Чугунная улица, 14',
                        'street': 'Чугунная улица'},
            'adv_context': None,
            'adv_response_url': None,
            'alternate_url': 'https://hh.ru/vacancy/93091375',
            'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=93091375',
            'archived': False,
            'area': {'id': '2',
                     'name': 'Санкт-Петербург',
                     'url': 'https://api.hh.ru/areas/2'},
            'contacts': {'email': 'kowtal@mail.ru',
                         'name': 'Ковтун Алексей',
                         'phones': [{'city': '905',
                                     'comment': None,
                                     'country': '7',
                                     'formatted': '+79052031463',
                                     'number': '2031463'},
                                    {'city': '905',
                                     'comment': None,
                                     'country': '7',
                                     'formatted': '+79052031463',
                                     'number': '2031463'}]},
            'created_at': '2024-02-27T16:27:43+0300',
            'department': None,
            'employer': {'accredited_it_employer': False,
                         'alternate_url': 'https://hh.ru/employer/4698004',
                         'id': '4698004',
                         'logo_urls': {'240': 'https://hhcdn.ru/employer-logo/5736489.jpeg',
                                       '90': 'https://hhcdn.ru/employer-logo/5736488.jpeg',
                                       'original': 'https://hhcdn.ru/employer-logo-original/1028932.jpg'},
                         'name': 'Woodhouse',
                         'trusted': True,
                         'url': 'https://api.hh.ru/employers/4698004',
                         'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=4698004'},
            'employment': {'id': 'full', 'name': 'Полная занятость'},
            'experience': {'id': 'between3And6', 'name': 'От 3 до 6 лет'},
            'has_test': False,
            'id': '93091375',
            'insider_interview': None,
            'is_adv_vacancy': False,
            'name': 'Столяр',
            'premium': False,
            'professional_roles': [{'id': '40', 'name': 'Другое'}],
            'published_at': '2024-02-27T16:27:43+0300',
            'relations': [],
            'response_letter_required': False,
            'response_url': None,
            'salary': {'currency': 'RUR',
                       'from': 90000,
                       'gross': False,
                       'to': 140000},
            'schedule': {'id': 'fullDay', 'name': 'Полный день'},
            'show_logo_in_search': None,
            'snippet': {'requirement': 'Опыт работы с изделиями из массива, '
                                       'МДФ, шпона обязателен!- Обязательное '
                                       'требование - умение работать на '
                                       'станках и ручным инструментом. - ',
                        'responsibility': 'Изготовление изделий по чертежам. - '
                                          'Изготовление предметов мебели, '
                                          'элементов интерьера. - Монтаж и '
                                          'подгон готовых изделий на объекте. '
                                          '- Соблюдение внутреннего распорядка '
                                          'и...'},
            'sort_point_distance': None,
            'type': {'id': 'open', 'name': 'Открытая'},
            'url': 'https://api.hh.ru/vacancies/93091375?host=hh.ru',
            'working_days': [],
            'working_time_intervals': [],
            'working_time_modes': []},
           {'accept_incomplete_resumes': True,
            'accept_temporary': False,
            'address': {'building': '74А',
                        'city': 'Дедовск',
                        'description': None,
                        'id': '15216499',
                        'lat': 55.87995,
                        'lng': 37.119771,
                        'metro': None,
                        'metro_stations': [],
                        'raw': 'Дедовск, 1-я Волоколамская улица, 74А',
                        'street': '1-я Волоколамская улица'},
            'adv_context': None,
            'adv_response_url': None,
            'alternate_url': 'https://hh.ru/vacancy/93620509',
            'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=93620509',
            'archived': False,
            'area': {'id': '2100',
                     'name': 'Дедовск',
                     'url': 'https://api.hh.ru/areas/2100'},
            'contacts': None,
            'created_at': '2024-02-27T16:08:54+0300',
            'department': None,
            'employer': {'accredited_it_employer': False,
                         'alternate_url': 'https://hh.ru/employer/10816694',
                         'id': '10816694',
                         'logo_urls': None,
                         'name': 'Софронова Марина Юрьевна',
                         'trusted': True,
                         'url': 'https://api.hh.ru/employers/10816694',
                         'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=10816694'},
            'employment': {'id': 'full', 'name': 'Полная занятость'},
            'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
            'has_test': False,
            'id': '93620509',
            'insider_interview': None,
            'is_adv_vacancy': False,
            'name': 'Столяр',
            'premium': False,
            'professional_roles': [{'id': '40', 'name': 'Другое'}],
            'published_at': '2024-02-27T16:08:54+0300',
            'relations': [],
            'response_letter_required': False,
            'response_url': None,
            'salary': {'currency': 'RUR',
                       'from': 60000,
                       'gross': False,
                       'to': 120000},
            'schedule': {'id': 'fullDay', 'name': 'Полный день'},
            'snippet': {'requirement': 'Опыт не менее 1 года. Умение читать '
                                       'чертежи. Умение работать со шпоном.',
                        'responsibility': 'Производство мебели и столярных '
                                          'изделий на заказ. Работа на '
                                          'территории предприятия. Выезд на '
                                          'монтаж произведенных изделий.'},
            'sort_point_distance': None,
            'type': {'id': 'open', 'name': 'Открытая'},
            'url': 'https://api.hh.ru/vacancies/93620509?host=hh.ru',
            'working_days': [],
            'working_time_intervals': [],
            'working_time_modes': []},
           {'accept_incomplete_resumes': True,
            'accept_temporary': True,
            'address': {'building': '11Р',
                        'city': 'деревня Малые Вязёмы',
                        'description': None,
                        'id': '14595089',
                        'lat': 55.6388311862491,
                        'lng': 37.02997008324944,
                        'metro': None,
                        'metro_stations': [],
                        'raw': 'деревня Малые Вязёмы, 11Р',
                        'street': None},
            'adv_context': None,
            'adv_response_url': None,
            'alternate_url': 'https://hh.ru/vacancy/93880192',
            'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=93880192',
            'archived': False,
            'area': {'id': '2053',
                     'name': 'Одинцово',
                     'url': 'https://api.hh.ru/areas/2053'},
            'contacts': {'email': 'sales@beni.ru',
                         'name': 'Елена',
                         'phones': [{'city': '915',
                                     'comment': None,
                                     'country': '7',
                                     'formatted': '+79150954103',
                                     'number': '0954103'},
                                    {'city': '916',
                                     'comment': None,
                                     'country': '7',
                                     'formatted': '+79169688796',
                                     'number': '9688796'}]},
            'created_at': '2024-02-27T15:24:24+0300',
            'department': None,
            'employer': {'accredited_it_employer': False,
                         'alternate_url': 'https://hh.ru/employer/3052397',
                         'id': '3052397',
                         'logo_urls': {'240': 'https://hhcdn.ru/employer-logo/6379606.jpeg',
                                       '90': 'https://hhcdn.ru/employer-logo/6379605.jpeg',
                                       'original': 'https://hhcdn.ru/employer-logo-original/1189787.jpg'},
                         'name': 'БЕНИ',
                         'trusted': True,
                         'url': 'https://api.hh.ru/employers/3052397',
                         'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=3052397'},
            'employment': {'id': 'full', 'name': 'Полная занятость'},
            'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
            'has_test': False,
            'id': '93880192',
            'insider_interview': None,
            'is_adv_vacancy': False,
            'name': 'Столяр',
            'premium': False,
            'professional_roles': [{'id': '85',
                                    'name': 'Оператор производственной линии'}],
            'published_at': '2024-02-27T15:24:24+0300',
            'relations': [],
            'response_letter_required': False,
            'response_url': None,
            'salary': {'currency': 'RUR',
                       'from': 80000,
                       'gross': False,
                       'to': 200000},
            'schedule': {'id': 'fullDay', 'name': 'Полный день'},
            'show_logo_in_search': None,
            'snippet': {'requirement': 'Опыт работы в мебельном производстве '
                                       'не менее 1 года. Образование не ниже '
                                       'среднего специального, умение читать '
                                       'чертежи, ответственность, '
                                       'внимательность. ',
                        'responsibility': 'Изготовление изделий по '
                                          'индивидуальным проектам. '
                                          'Изготовление мебельных изделий из '
                                          'массива дерева, МДФ, шпон, фанеры. '
                                          'Сборка мебели по индивидуальным '
                                          'проектам на...'},
            'sort_point_distance': None,
            'type': {'id': 'open', 'name': 'Открытая'},
            'url': 'https://api.hh.ru/vacancies/93880192?host=hh.ru',
            'working_days': [{'id': 'only_saturday_and_sunday',
                              'name': 'Работа только по\xa0сб\xa0и\xa0вс'}],
            'working_time_intervals': [],
            'working_time_modes': [{'id': 'start_after_sixteen',
                                    'name': 'Можно начинать работать после '
                                            '16:00'}]},
           {'accept_incomplete_resumes': True,
            'accept_temporary': True,
            'address': {'building': '4А',
                        'city': 'Пермь 56.243556, 58.016991',
                        'description': None,
                        'id': '14906571',
                        'lat': 58.016991,
                        'lng': 56.243556,
                        'metro': None,
                        'metro_stations': [],
                        'raw': 'Пермь 56.243556, 58.016991, Сибирская улица, '
                               '4А',
                        'street': 'Сибирская улица'},
            'adv_context': None,
            'adv_response_url': None,
            'alternate_url': 'https://hh.ru/vacancy/92470848',
            'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=92470848',
            'archived': False,
            'area': {'id': '72',
                     'name': 'Пермь',
                     'url': 'https://api.hh.ru/areas/72'},
            'contacts': {'email': 'liza.kalugina2009@yandex.ru',
                         'name': 'Елизавета Калугина',
                         'phones': [{'city': '912',
                                     'comment': 'Звонить в рабочее время',
                                     'country': '7',
                                     'formatted': '+79124979772',
                                     'number': '4979772'}]},
            'created_at': '2024-02-27T14:37:55+0300',
            'department': None,
            'employer': {'accredited_it_employer': False,
                         'alternate_url': 'https://hh.ru/employer/10670208',
                         'id': '10670208',
                         'logo_urls': None,
                         'name': 'Калугина Елизавета Андреевна',
                         'trusted': True,
                         'url': 'https://api.hh.ru/employers/10670208',
                         'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=10670208'},
            'employment': {'id': 'full', 'name': 'Полная занятость'},
            'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
            'has_test': False,
            'id': '92470848',
            'insider_interview': None,
            'is_adv_vacancy': False,
            'name': 'Столяр',
            'premium': False,
            'professional_roles': [{'id': '40', 'name': 'Другое'}],
            'published_at': '2024-02-27T14:37:55+0300',
            'relations': [],
            'response_letter_required': False,
            'response_url': None,
            'salary': {'currency': 'RUR',
                       'from': 40000,
                       'gross': False,
                       'to': 50000},
            'schedule': {'id': 'fullDay', 'name': 'Полный день'},
            'snippet': {'requirement': 'Разбираться в: В методах работы с '
                                       'разнообразными сортами дерева.',
                        'responsibility': 'Производить столярные и ремонтные '
                                          'работы с малогабаритной мебелью. '
                                          'Производить склейку деревянных '
                                          'деталей и их поверхностью. Чистить '
                                          'деревянные поверхности, а также...'},
            'sort_point_distance': None,
            'type': {'id': 'open', 'name': 'Открытая'},
            'url': 'https://api.hh.ru/vacancies/92470848?host=hh.ru',
            'working_days': [],
            'working_time_intervals': [],
            'working_time_modes': []},
           {'accept_incomplete_resumes': True,
            'accept_temporary': False,
            'address': {'building': None,
                        'city': 'посёлок Зелёный',
                        'description': None,
                        'id': '15249092',
                        'lat': 55.809171,
                        'lng': 38.098791,
                        'metro': None,
                        'metro_stations': [],
                        'raw': 'посёлок Зелёный',
                        'street': None},
            'adv_context': None,
            'adv_response_url': None,
            'alternate_url': 'https://hh.ru/vacancy/93874006',
            'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=93874006',
            'archived': False,
            'area': {'id': '1',
                     'name': 'Москва',
                     'url': 'https://api.hh.ru/areas/1'},
            'contacts': None,
            'created_at': '2024-02-27T14:14:19+0300',
            'department': None,
            'employer': {'accredited_it_employer': False,
                         'alternate_url': 'https://hh.ru/employer/10832438',
                         'id': '10832438',
                         'logo_urls': None,
                         'name': 'Попов Алексей Николаевич \u200b \u200b',
                         'trusted': True,
                         'url': 'https://api.hh.ru/employers/10832438',
                         'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=10832438'},
            'employment': {'id': 'full', 'name': 'Полная занятость'},
            'experience': {'id': 'between3And6', 'name': 'От 3 до 6 лет'},
            'has_test': False,
            'id': '93874006',
            'insider_interview': None,
            'is_adv_vacancy': False,
            'name': 'Столяр',
            'premium': False,
            'professional_roles': [{'id': '40', 'name': 'Другое'}],
            'published_at': '2024-02-27T14:14:19+0300',
            'relations': [],
            'response_letter_required': False,
            'response_url': None,
            'salary': {'currency': 'RUR',
                       'from': 120000,
                       'gross': False,
                       'to': 150000},
            'schedule': {'id': 'fullDay', 'name': 'Полный день'},
            'snippet': {'requirement': 'Опыт работы по специальности.',
                        'responsibility': 'Изготовление мебели на заказ. МДФ, '
                                          'шпон, массив.'},
            'sort_point_distance': None,
            'type': {'id': 'open', 'name': 'Открытая'},
            'url': 'https://api.hh.ru/vacancies/93874006?host=hh.ru',
            'working_days': [],
            'working_time_intervals': [],
            'working_time_modes': []},
           {'accept_incomplete_resumes': True,
            'accept_temporary': True,
            'address': {'building': '9П',
                        'city': 'Челябинск',
                        'description': None,
                        'id': '14885253',
                        'lat': 55.11812903012027,
                        'lng': 61.53096645899866,
                        'metro': None,
                        'metro_stations': [],
                        'raw': 'Челябинск, Копейское шоссе, 9П',
                        'street': 'Копейское шоссе'},
            'adv_context': None,
            'adv_response_url': None,
            'alternate_url': 'https://hh.ru/vacancy/93077053',
            'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=93077053',
            'archived': False,
            'area': {'id': '104',
                     'name': 'Челябинск',
                     'url': 'https://api.hh.ru/areas/104'},
            'contacts': {'email': 'scharapov.evg@gmail.com',
                         'name': 'Шарапов Евгений',
                         'phones': [{'city': '995',
                                     'comment': None,
                                     'country': '7',
                                     'formatted': '+79954685212',
                                     'number': '4685212'}]},
            'created_at': '2024-02-27T13:53:39+0300',
            'department': None,
            'employer': {'accredited_it_employer': False,
                         'alternate_url': 'https://hh.ru/employer/8934007',
                         'id': '8934007',
                         'logo_urls': {'240': 'https://hhcdn.ru/employer-logo/5510553.jpeg',
                                       '90': 'https://hhcdn.ru/employer-logo/5510552.jpeg',
                                       'original': 'https://hhcdn.ru/employer-logo-original/972426.jpeg'},
                         'name': 'Уральские Банные Чаны',
                         'trusted': True,
                         'url': 'https://api.hh.ru/employers/8934007',
                         'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=8934007'},
            'employment': {'id': 'full', 'name': 'Полная занятость'},
            'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
            'has_test': False,
            'id': '93077053',
            'insider_interview': None,
            'is_adv_vacancy': False,
            'name': 'Столяр',
            'premium': False,
            'professional_roles': [{'id': '40', 'name': 'Другое'}],
            'published_at': '2024-02-27T13:53:39+0300',
            'relations': [],
            'response_letter_required': False,
            'response_url': None,
            'salary': {'currency': 'RUR',
                       'from': 70000,
                       'gross': False,
                       'to': 100000},
            'schedule': {'id': 'fullDay', 'name': 'Полный день'},
            'show_logo_in_search': None,
            'snippet': {'requirement': 'Аккуратность в работе. Строгое '
                                       'соблюдение распорядка. Умение работать '
                                       'с электроинструментом.',
                        'responsibility': 'Напил заготовок из доски, бруска. '
                                          'Шлифовка заготовок из древесины. '
                                          'Покрытие заготовок пропиткой. '
                                          'Установка деревянной отделки в '
                                          'банный чан. '},
            'sort_point_distance': None,
            'type': {'id': 'open', 'name': 'Открытая'},
            'url': 'https://api.hh.ru/vacancies/93077053?host=hh.ru',
            'working_days': [],
            'working_time_intervals': [],
            'working_time_modes': []},
           {'accept_incomplete_resumes': True,
            'accept_temporary': False,
            'address': {'building': '11А',
                        'city': 'Подольск',
                        'description': None,
                        'id': '12291284',
                        'lat': 55.408291,
                        'lng': 37.577894,
                        'metro': {'lat': 55.431667,
                                  'line_id': '132',
                                  'line_name': 'МЦД - 2',
                                  'lng': 37.565,
                                  'station_id': '132.743',
                                  'station_name': 'Подольск'},
                        'metro_stations': [{'lat': 55.431667,
                                            'line_id': '132',
                                            'line_name': 'МЦД - 2',
                                            'lng': 37.565,
                                            'station_id': '132.743',
                                            'station_name': 'Подольск'}],
                        'raw': 'Подольск, улица Машиностроителей, 11А',
                        'street': 'улица Машиностроителей'},
            'adv_context': None,
            'adv_response_url': None,
            'alternate_url': 'https://hh.ru/vacancy/93866563',
            'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=93866563',
            'archived': False,
            'area': {'id': '2061',
                     'name': 'Подольск (Московская область)',
                     'url': 'https://api.hh.ru/areas/2061'},
            'contacts': {'email': 'a.v.kiyanova.mtm@gmail.com',
                         'name': 'Киянова Анна Владимировна',
                         'phones': [{'city': '910',
                                     'comment': None,
                                     'country': '7',
                                     'formatted': '+79106333500',
                                     'number': '6333500'}]},
            'created_at': '2024-02-27T12:48:29+0300',
            'department': None,
            'employer': {'accredited_it_employer': False,
                         'alternate_url': 'https://hh.ru/employer/5708314',
                         'id': '5708314',
                         'logo_urls': {'240': 'https://hhcdn.ru/employer-logo/4041392.png',
                                       '90': 'https://hhcdn.ru/employer-logo/4041391.png',
                                       'original': 'https://hhcdn.ru/employer-logo-original/900176.png'},
                         'name': 'Фабрика мебели МТМ',
                         'trusted': True,
                         'url': 'https://api.hh.ru/employers/5708314',
                         'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=5708314'},
            'employment': {'id': 'full', 'name': 'Полная занятость'},
            'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
            'has_test': False,
            'id': '93866563',
            'insider_interview': None,
            'is_adv_vacancy': False,
            'name': 'Столяр',
            'premium': False,
            'professional_roles': [{'id': '40', 'name': 'Другое'}],
            'published_at': '2024-02-27T12:48:29+0300',
            'relations': [],
            'response_letter_required': False,
            'response_url': None,
            'salary': {'currency': 'RUR',
                       'from': 100000,
                       'gross': True,
                       'to': None},
            'schedule': {'id': 'fullDay', 'name': 'Полный день'},
            'show_logo_in_search': None,
            'snippet': {'requirement': 'Навык работы с чертежами и эскизами. '
                                       'Опыт работы с индивидуальными '
                                       'заказами. Опыт работы на '
                                       'деревообрабатывающих станках.',
                        'responsibility': 'Изготовление и сборка корпусной '
                                          'мебели, индивидуальных изделий из '
                                          'ДСП, МДФ и массива. Работа на '
                                          'деревообрабатывающих станках. '
                                          'Шпонирование натуральным шпоном.'},
            'sort_point_distance': None,
            'type': {'id': 'open', 'name': 'Открытая'},
            'url': 'https://api.hh.ru/vacancies/93866563?host=hh.ru',
            'working_days': [],
            'working_time_intervals': [],
            'working_time_modes': []},
           {'accept_incomplete_resumes': True,
            'accept_temporary': False,
            'address': {'building': '68к3',
                        'city': 'Воронеж',
                        'description': None,
                        'id': '3447893',
                        'lat': 51.671489,
                        'lng': 39.124155,
                        'metro': None,
                        'metro_stations': [],
                        'raw': 'Воронеж, Холмистая улица, 68к3',
                        'street': 'Холмистая улица'},
            'adv_context': None,
            'adv_response_url': None,
            'alternate_url': 'https://hh.ru/vacancy/90152546',
            'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=90152546',
            'archived': False,
            'area': {'id': '26',
                     'name': 'Воронеж',
                     'url': 'https://api.hh.ru/areas/26'},
            'contacts': {'email': 'ok@hoztorgvrn.ru',
                         'name': 'Яна',
                         'phones': [{'city': '951',
                                     'comment': None,
                                     'country': '7',
                                     'formatted': '+79518701229',
                                     'number': '8701229'}]},
            'created_at': '2024-02-27T12:45:45+0300',
            'department': None,
            'employer': {'accredited_it_employer': False,
                         'alternate_url': 'https://hh.ru/employer/1304799',
                         'id': '1304799',
                         'logo_urls': {'240': 'https://hhcdn.ru/employer-logo/3191789.jpeg',
                                       '90': 'https://hhcdn.ru/employer-logo/3191788.jpeg',
                                       'original': 'https://hhcdn.ru/employer-logo-original/687664.jpg'},
                         'name': 'Объединение Хозторг',
                         'trusted': True,
                         'url': 'https://api.hh.ru/employers/1304799',
                         'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=1304799'},
            'employment': {'id': 'full', 'name': 'Полная занятость'},
            'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
            'has_test': False,
            'id': '90152546',
            'insider_interview': None,
            'is_adv_vacancy': False,
            'name': 'Столяр',
            'premium': False,
            'professional_roles': [{'id': '40', 'name': 'Другое'}],
            'published_at': '2024-02-27T12:45:45+0300',
            'relations': [],
            'response_letter_required': False,
            'response_url': None,
            'salary': {'currency': 'RUR',
                       'from': 40000,
                       'gross': False,
                       'to': None},
            'schedule': {'id': 'fullDay', 'name': 'Полный день'},
            'show_logo_in_search': None,
            'snippet': {'requirement': 'Опыт работы на деревообрабатывающих '
                                       'станках. Опыт изготовления и сборки '
                                       'столярных изделий средней сложности. '
                                       'Работа с чертежами.',
                        'responsibility': 'Работа на деревообрабатывающих '
                                          'станках. Изготовление изделий из '
                                          'дерева.'},
            'sort_point_distance': None,
            'type': {'id': 'open', 'name': 'Открытая'},
            'url': 'https://api.hh.ru/vacancies/90152546?host=hh.ru',
            'working_days': [],
            'working_time_intervals': [],
            'working_time_modes': []},
           {'accept_incomplete_resumes': False,
            'accept_temporary': False,
            'address': {'building': '98Е',
                        'city': 'Пермь',
                        'description': None,
                        'id': '4958025',
                        'lat': 57.983983,
                        'lng': 56.254947,
                        'metro': None,
                        'metro_stations': [],
                        'raw': 'Пермь, Комсомольский проспект, 98Е',
                        'street': 'Комсомольский проспект'},
            'adv_context': None,
            'adv_response_url': None,
            'alternate_url': 'https://hh.ru/vacancy/93861114',
            'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=93861114',
            'archived': False,
            'area': {'id': '72',
                     'name': 'Пермь',
                     'url': 'https://api.hh.ru/areas/72'},
            'contacts': {'email': 'disiar1@yandex.ru',
                         'name': 'Кулаков Андрей Николаевич',
                         'phones': [{'city': '908',
                                     'comment': 'Звоните смелее',
                                     'country': '7',
                                     'formatted': '+79082720138',
                                     'number': '2720138'},
                                    {'city': '908',
                                     'comment': None,
                                     'country': '7',
                                     'formatted': '+79082720138',
                                     'number': '2720138'}]},
            'created_at': '2024-02-27T11:56:01+0300',
            'department': None,
            'employer': {'accredited_it_employer': False,
                         'alternate_url': 'https://hh.ru/employer/4741542',
                         'id': '4741542',
                         'logo_urls': None,
                         'name': 'Торгово-производственная компания AMBIZIOZO',
                         'trusted': True,
                         'url': 'https://api.hh.ru/employers/4741542',
                         'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=4741542'},
            'employment': {'id': 'full', 'name': 'Полная занятость'},
            'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
            'has_test': False,
            'id': '93861114',
            'insider_interview': None,
            'is_adv_vacancy': False,
            'name': 'Столяр',
            'premium': False,
            'professional_roles': [{'id': '40', 'name': 'Другое'}],
            'published_at': '2024-02-27T11:56:01+0300',
            'relations': [],
            'response_letter_required': False,
            'response_url': None,
            'salary': {'currency': 'RUR',
                       'from': 55000,
                       'gross': False,
                       'to': 85000},
            'schedule': {'id': 'fullDay', 'name': 'Полный день'},
            'snippet': {'requirement': 'Опыт работы на производстве мебели , '
                                       'опыт работы с деревообрабатывающим '
                                       'электроинструментом. Внимательность , '
                                       'аккуратность , пунктуальность , '
                                       'ответственность.',
                        'responsibility': 'Раскрой древесины, обработка , '
                                          'распил , сборка каркасов мебели , '
                                          'шлифование , покраска каркасов '
                                          'диванов , кресел , кроватей и '
                                          'другой мягкой мебели.'},
            'sort_point_distance': None,
            'type': {'id': 'open', 'name': 'Открытая'},
            'url': 'https://api.hh.ru/vacancies/93861114?host=hh.ru',
            'working_days': [],
            'working_time_intervals': [],
            'working_time_modes': []},
           {'accept_incomplete_resumes': True,
            'accept_temporary': True,
            'address': None,
            'adv_context': None,
            'adv_response_url': None,
            'alternate_url': 'https://hh.ru/vacancy/93859290',
            'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=93859290',
            'archived': False,
            'area': {'id': '89',
                     'name': 'Тверь',
                     'url': 'https://api.hh.ru/areas/89'},
            'contacts': {'email': 'smirnova.y.s@yandex.ru',
                         'name': 'Яна',
                         'phones': [{'city': '910',
                                     'comment': None,
                                     'country': '7',
                                     'formatted': '+79106465850',
                                     'number': '6465850'}]},
            'created_at': '2024-02-27T11:41:25+0300',
            'department': None,
            'employer': {'accredited_it_employer': False,
                         'alternate_url': 'https://hh.ru/employer/9771293',
                         'id': '9771293',
                         'logo_urls': {'240': 'https://hhcdn.ru/employer-logo/6486714.jpeg',
                                       '90': 'https://hhcdn.ru/employer-logo/6486713.jpeg',
                                       'original': 'https://hhcdn.ru/employer-logo-original/1216567.jpeg'},
                         'name': 'Техинжиниринг',
                         'trusted': True,
                         'url': 'https://api.hh.ru/employers/9771293',
                         'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=9771293'},
            'employment': {'id': 'full', 'name': 'Полная занятость'},
            'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'},
            'has_test': False,
            'id': '93859290',
            'insider_interview': None,
            'is_adv_vacancy': False,
            'name': 'Столяр',
            'premium': False,
            'professional_roles': [{'id': '40', 'name': 'Другое'}],
            'published_at': '2024-02-27T11:41:25+0300',
            'relations': [],
            'response_letter_required': False,
            'response_url': None,
            'salary': {'currency': 'RUR',
                       'from': 100000,
                       'gross': False,
                       'to': None},
            'schedule': {'id': 'flyInFlyOut', 'name': 'Вахтовый метод'},
            'show_logo_in_search': None,
            'snippet': {'requirement': None, 'responsibility': None},
            'sort_point_distance': None,
            'type': {'id': 'open', 'name': 'Открытая'},
            'url': 'https://api.hh.ru/vacancies/93859290?host=hh.ru',
            'working_days': [],
            'working_time_intervals': [],
            'working_time_modes': []}],
 'page': 0,
 'pages': 107,
 'per_page': 10,
 'suggests': None}